
export const factorynew = [
    {
        id: 1,
        maker: "BMW",
        title: "BMW M5 CS Deep Green Metallica",
        fuel: "Petrol",
        transmission: "Automatic",
        mileage: 0,
        model_year: 2022,
        model: "BMW M5",
        type: "Sedan",
        drivetrain: "Four-wheel",
        horsepower: 635,
        motorsize: 4395,
        price: 200.000,
        url: "https://media.discordapp.net/attachments/743211223826563081/1003398446427938826/id1new.jpg?width=697&height=523",
    },
    {
        id: 2,
        maker: "BMW",
        title: "BMW M5 Competition 625HP",
        fuel: "Petrol",
        transmission: "Automatic",
        mileage: 0,
        model_year: 2021,
        model: "BMW M5",
        type: "Sedan",
        drivetrain: "Four-wheel",
        horsepower: 626,
        motorsize: 4395,
        price: 130.000,
        url: "https://i.blocketcdn.se/pictures/5954619862.webp?type=original",


    },
    {
        id: 3,
        maker: "BMW",
        title: "BMW M5 (625HP) Competition",
        fuel: "Petrol",
        transmission: "Automatic",
        mileage: 0,
        model_year: 2021,
        model: "BMW M5",
        type: "Sedan",
        drivetrain: "Four-wheel",
        horsepower: 626,
        motorsize: 4395,
        price: 126.000,
        url: "https://images-ext-1.discordapp.net/external/q8yfLEHbm4dyFlvhlTk5aEpHwQ9qd96Bcwol9TtlVA8/%3Ftype%3Doriginal/https/i.blocketcdn.se/pictures/2623623179.webp?width=840&height=630",


    },
    {
        id: 4,
        maker: "BMW",
        title: "BMW M5 Competition Package B&W",
        fuel: "Petrol",
        transmission: "Automatic",
        mileage: 0,
        model_year: 2021,
        model: "BMW M5",
        type: "Sedan",
        drivetrain: "Four-wheel",
        horsepower: 626,
        motorsize: 4395,
        price: 126.000,
        url: "https://images-ext-1.discordapp.net/external/qT6C4lzKVWwxuzyjBVAKBn0WLps57I32iBDOZPpPqO8/%3Ftype%3Doriginal/https/i.blocketcdn.se/pictures/9398425952.webp?width=945&height=630",


    },
    {
        id: 5,
        maker: "BMW",
        title: "BMW M5 Competition",
        fuel: "Petrol",
        transmission: "Automatic",
        mileage: 0,
        model_year: 2020,
        model: "BMW M5",
        type: "Sedan",
        drivetrain: "Four-wheel",
        horsepower: 626,
        motorsize: 4395,
        price: 104.000,
        url: "https://images-ext-2.discordapp.net/external/WT6Ny2CY_Q5BM7lFxPsYc1SIsE8m9Qt8maWnbfS6iMs/%3Ftype%3Doriginal/https/i.blocketcdn.se/pictures/8596052395.webp?width=840&height=630",


    },
    {
        id: 6,
        maker: "BMW",
        title: "BMW M5 F90 xDrive",
        fuel: "Petrol",
        transmission: "Automatic",
        mileage: 2975,
        model_year: 2018,
        model: "BMW M5",
        type: "Sedan",
        drivetrain: "Four-wheel",
        horsepower: 600,
        motorsize: 4395,
        price: 94.500,
        url: "https://images-ext-2.discordapp.net/external/lk_b__v5BVlAM-hzrzV6g57z98p3MSGlUNbCYRXNdHc/%3Ftype%3Doriginal/https/i.blocketcdn.se/pictures/0080282404.webp?width=945&height=630",


    },
    {
        id: 7,
        maker: "BMW",
        title: "BMW M5 Competition Euro 6",
        fuel: "Petrol",
        transmission: "Automatic",
        mileage: 5100,
        model_year: 2019,
        model: "BMW M5",
        type: "Sedan",
        drivetrain: "Four-wheel",
        horsepower: 626,
        motorsize: 4395,
        price: 89.000,
        url: "https://images-ext-2.discordapp.net/external/jhdJOhlkdG83EurxDTR3a7GyqEeJ3yhkkn_X5G5oHqI/%3Ftype%3Doriginal/https/i.blocketcdn.se/pictures/7952283776.webp?width=840&height=630",


    },
    {
        id: 8,
        maker: "BMW",
        title: "BMW M5 Competition",
        fuel: "Petrol",
        transmission: "Automatic",
        mileage: 6925,
        model_year: 2019,
        model: "BMW M5",
        type: "Sedan",
        drivetrain: "Four-wheel",
        horsepower: 626,
        motorsize: 4395,
        price: 89.900,
        url: "https://images-ext-2.discordapp.net/external/YWABisT0-cTiYzb4xoxenDRZJKoIqmZHWDtqv22avDQ/%3Ftype%3Doriginal/https/i.blocketcdn.se/pictures/9874683636.webp?width=945&height=630",


    },
    {
        id: 9,
        maker: "BMW",
        title: "BMW M5 Competition",
        fuel: "Petrol",
        transmission: "Automatic",
        mileage: 1700,
        model_year: 2017,
        model: "BMW M5",
        type: "Sedan",
        drivetrain: "Four-wheel",
        horsepower: 600,
        motorsize: 4395,
        price: 73.000,
        url: "https://images-ext-2.discordapp.net/external/_Ogk56DPba5tWJLgDLNAKIo8L6FvV0Vd2LA8ixoVip0/%3Ftype%3Doriginal/https/i.blocketcdn.se/pictures/3171059701.webp?width=945&height=630",


    },
    {
        id: 10,
        maker: "BMW",
        title: "BMW M5 Competition",
        fuel: "Petrol",
        transmission: "Automatic",
        mileage: 4802,
        model_year: 2016,
        model: "BMW M5",
        type: "Sedan",
        drivetrain: "Four-wheel",
        horsepower: 600,
        motorsize: 4395,
        price: 69.900,
        url: "https://images-ext-1.discordapp.net/external/u-Whg9VP3DiJ7TshZGVxCGHaHB7eIzq0wrWm9ybU7dI/%3Ftype%3Doriginal/https/i.blocketcdn.se/pictures/0416455385.webp?width=945&height=630",


    },
    {
        id: 11,
        maker: "BMW",
        title: "BMW M3 xDrive Competition",
        fuel: "Petrol",
        transmission: "Automatic",
        mileage: 0,
        model_year: 2022,
        model: "BMW M3",
        type: "Sedan",
        drivetrain: "Four-wheel",
        horsepower: 510,
        motorsize: 2993,
        price: 104.900,
        url: "https://images-ext-2.discordapp.net/external/Ws_mWOIFmZB3LBPev4RFPnndhx8nFZuAnAx8gCQxdo0/%3Ftype%3Doriginal/https/i.blocketcdn.se/pictures/0584972381.webp?width=840&height=630",
    },
    



]